# yaml-language-server: $schema=../../schemas/network.schema.json

# omega0 = 1.0 (mass)
# g = 9.81 (gravity)
# l = 1.0 (length of the pendulum)

network:
  name: "DGU"

  systems:
    # Combined system representing the full DC power network
    # In this example, we define it as a single system
    # (Could be split into multiple interconnected subsystems)
    # R_i = 0.1
    # L_i = 0.018
    # C_i = 0.000025
    - id: "dgu"
      components:
        - id: Id
          dissipation: 0.1
          mass: 55.5555555556
          x0: 161.07
        - id: Iq
          dissipation: 0.1
          mass: 55.5555555556
          x0: 161.07
        - id: Vd
          dissipation: 0
          mass: 40000
          x0: 20000
        - id: Vq
          dissipation: 0
          mass: 40000
          x0: 20000
      connections:
        - from: Id
          to: Iq
          weight: 5.6548
        - from: Id
          to: Vd
          weight: -1
        - from: Iq
          to: Vq
          weight: -1
        - from: Vd
          to: Vq
          weight: 0.00785398163
      ports:
        p1: Id
        p2: Iq
        p3: Vd
        p4: Vq

        # PI Controller subsystem
    - id: "controller_d"
      components:
        - id: integral
          dissipation: 0 # Check this value
          mass: 0.0666667
          x0: 0
        - id: proportional
          dissipation: 1 # Check this value
          mass: 0.1
          x0: 0
      connections:
        - from: integral
          to: proportional
          weight: 1
      ports:
        p1: proportional

    - id: "controller_q"
      components:
        - id: integral
          dissipation: 0 # Check this value
          mass: 0.0666667
          x0: 0
        - id: proportional
          dissipation: 1 # Check this value
          mass: 0.1
          x0: 0
      connections:
        - from: integral
          to: proportional
          weight: 1
      ports:
        p2: proportional

    - id: "Line"
      components:
        - id: Id
          dissipation: 0.343
          mass: 1142.85714286
          x0: 161.07
        - id: Iq
          dissipation: 0.343
          mass: 1142.85714286
          x0: 161.07
      connections:
        - from: Id
          to: Iq
          weight: 0.274889357
      ports:
        p1: Id
        p2: Iq

    - id: "Load"
      components:
        - id: Id
          dissipation: 2.9154
          mass: 1.1428
          x0: 161.07
        - id: Iq
          dissipation: 2.9154
          mass: 1.1428
          x0: 161.07
      connections:
        - from: Id
          to: Iq
          weight: 274.8893
      ports:
        p1: Id
        p2: Iq

  connections:
    - from:
        system: dgu
        port: p1
      to:
        system: controller_d
        port: p1
      weight: -1
    - from:
        system: dgu
        port: p2
      to:
        system: controller_q
        port: p2
      weight: -1
    - from:
        system: dgu
        port: p3
      to:
        system: Line
        port: p1
      weight: -1
    - from:
        system: dgu
        port: p4
      to:
        system: Line
        port: p2
      weight: -1
    - from:
        system: Line
        port: p1
      to:
        system: Load
        port: p1
      weight: 1
    - from:
        system: Line
        port: p2
      to:
        system: Load
        port: p2
      weight: 1

# Simulation configuration
simulation:
  time_span: [0, 1]
  solver: "IDA"
  timestep: 0.001
