# yaml-language-server: $schema=../../schemas/network.schema.json

# m = 1.0 (mass)
# g = 9.81 (gravity)
# l = 1.0 (length of the pendulum)

network:
  name: "Pendulum with PI Controller"

  systems:
    - id: "pendulum"
      matrices:
        J:
          - [0.0, 1.0]
          - [-1.0, 0.0]

        # No damping (diagonal)
        R: [0.0, 0.0]

        # Mass matrix (diagonal)
        Q: [9.81, 1.0] # m = 1, g = 9.81, l = 1

        B: [0.0, 1.0]

        x0: [0.1745, 0.0] # Initial angle (rad) and angular momentum

    # PI Controller subsystem
    - id: "controller"
      matrices:
        J:
          - [0.0, 1.0]
          - [-1.0, 0.0]

        # Damping / gain matrix (diagonal)
        R: [0.0, 20.0] # Proportional gain (Kp)

        # Storage matrix (diagonal)
        Q: [8.0, 0.1] # Integral gain (kI), Derivative gain (1/kD)

        B: [0.0, 1.0]

        x0: [0.0, 0.0] # Controller starts with zero integral and proportional states

  connections:
    - from: "pendulum"
      from_ports: [1]
      to: "controller"
      to_ports: [1]
      type: "negative_feedback"
    - from: "controller"
      from_ports: [1]
      to: "pendulum"
      to_ports: [1]
      type: "direct"

simulation:
  time_span: [0.0, 50.0]
  timestep: 0.1
  solver: "IDA"
